# Site settings
title: Antonio Lima's blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Scattered words.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://themiurgo.github.io" # the base hostname & protocol for your site
twitter_username: themiurgo
github_username:  themiurgo

# Build settings
markdown: kramdown
